#####################################################################################
# Server settings
server:
  port: 8080
  
#####################################################################################
# Eureka settings
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

#####################################################################################
# API GATEWAY settings
spring:
  cloud:
    gateway:
      routes:
      - id: ms-project
        uri: lb://MPM-MS-PROJECT
        predicates:
        - Path=/mpm-back/api/projects/**
        filters:
          - AddRequestHeader=origin,gateway-api
      - id: ms-project2
        uri: lb://MPM-MS-PROJECT
        predicates:
        - Path=/api/v1/projects/**
        filters:
          - AddRequestHeader=origin,gateway-api
          - RewritePath=/api/v1/projects(?<segment>/?.*), $\{segment}
          - SetPath=/mpm-back/api/projects
          
          
      - id: path_route
        uri: https://httpbin.org
        predicates:
        - Path=/new/post/**
        filters:
          - RewritePath=/new(?<segment>/?.*), $\{segment}
          - SetPath=/post
      - id: add_request_header_route
        uri: https://httpbin.org
        predicates:
        - Path=/get/**
        filters:
          - AddRequestHeader=My-Header-Good,Good
          - AddRequestHeader=My-Header-Remove,Remove
          - AddRequestParameter=var, good
          - AddRequestParameter=var2, remove
          - MapRequestHeader=My-Header-Good, My-Header-Bad
          - MapRequestHeader=My-Header-Set, My-Header-Bad
          - SetRequestHeader=My-Header-Set, Set 
          - RemoveRequestHeader=My-Header-Remove
          - RemoveRequestParameter=var2

#####################################################################################
# Logging settings
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
        
        