#####################################################################################
# Server settings
server:
  port: 8080
  
#####################################################################################
# Eureka settings
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

#####################################################################################
# API GATEWAY settings
spring:
  cloud:
    gateway:
      routes:
      - id: ms-project
        uri: lb://MPM-MS-PROJECT/mpm-back/api/projects
        predicates:
        - Path=/api/v1/projects/**
        
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
        
        