#####################################################################################
# Server settings
server:
  port: 8080
  
#####################################################################################
# Eureka settings
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

#####################################################################################
# API GATEWAY settings
spring:
  cloud:
    gateway:
      routes:
      - id: srv-auth
        uri: lb://MPM-SRV-AUTH
        predicates:
        - Path=/api/v1/auth/token
        filters:
          - AddRequestHeader=origin,gateway-api
          - AddResponseHeader=origin,server-auth
          - RewritePath=/api/v1/auth/token, /oauth/token
      - id: ms-project
        uri: lb://MPM-MS-PROJECT
        predicates:
        - Path=/api/v1/projects/**
        filters:
          - AddRequestHeader=origin,gateway-api
          - AddResponseHeader=origin,ms-backend
          - RewritePath=/api/v1/projects(?<segment>/?.*), /mpm-back/api/projects/$\{segment}